index:
    path: /
    controller: App\Controller\HomeController::index

registro:
    path: /registro
    controller: App\Controller\HomeController::crearPersona
    
imagen:
    path: /imagen
    controller: App\Controller\HomeController::index



